### DISCUSSION TITLE
Not respecting status code parameter

### DISCUSSION THREAD

**Discussion by klack** [tomMoulard/fail2ban#134] [General]
I cannot seem to get fail2ban to respect my `statuscode: "400,401,403-499"` parameter.  No mater what, I get banned with a status code of 200.  Can anyone take a look at my config?

`traefik.yaml`
```yml
experimental:
  plugins:
    fail2ban:
      moduleName: "github.com/tomMoulard/fail2ban"
      version: "v0.8.1"

global:
  checkNewVersion: false
  sendAnonymousUsage: false

# -- (Optional) Change Log Level and Format here...
#     - loglevels [DEBUG, INFO, WARNING, ERROR, CRITICAL]
#     - format [common, json, logfmt]
log:
  level: DEBUG
  format: common
  filePath: /var/log/traefik/traefik.log

# -- (Optional) Enable Accesslog and change Format here...
#     - format [common, json, logfmt]
# accesslog:
#   format: common
#   filePath: /var/log/traefik/access.log

# -- (Optional) Enable API and Dashboard here, don't do in production
api:
  dashboard: true
  disableDashboardAd: true
  insecure: true

# -- Change EntryPoints here...
entryPoints:
  web:
    address: :80
    # -- (Optional) Redirect all HTTP to HTTPS
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
  websecure:
    address: :443
  # -- (Optional) Add custom Entrypoint
  # custom:
  #   address: :8080
# -- (Optional) Disable TLS Cert verification check for services
# serversTransport:
#   insecureSkipVerify: true

# -- (Optional) Overwrite Default Certificates
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/suprim.crt
        keyFile: /etc/traefik/certs/suprim.key
  options:
    default:
      minVersion: VersionTLS12

providers:
  docker:
    # -- (Optional) Enable this, if you want to expose all containers automatically
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true
```
`dynamic.yaml`
```yml
http:
    middlewares:
        my-fail2ban:
            plugin:
                fail2ban:
                    logLevel: DEBUG
                    rules:
                      bantime: "3h"
                      findtime: "10m"
                      maxretry: 4
                      enabled: true
                      statuscode: "400,401,403-499"
```
`docker-compose.yml`
```yml
---
# -- (Optional) When using a custom network
networks:
  frontend:
    external: true

services:
  traefik:
    image: docker.io/library/traefik:v3.1.0
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      # -- (Optional) Enable Dashboard, don't do in production
      - 8080:8080
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/dynamic.yaml:/etc/traefik/dynamic.yaml
      - ./config/conf/:/etc/traefik/conf/
      - ./config/certs/:/etc/traefik/certs/
    networks:
      - frontend
    restart: unless-stopped

  whoami:
  #  A container that exposes an API to show its IP address
    image: traefik/whoami
    networks:
      - frontend    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=PathPrefix(`/`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"
      # - "traefik.http.middlewares.test-auth.basicauth.users=user:$$2y$$05$$ZN9YOxnmNHSLp3FOAohyQ.JpTmh15SpV/Hv6Dyu4.MefcHln92HaG"
      - "traefik.http.routers.whoami.middlewares=my-fail2ban@file"
```
