### DISCUSSION TITLE
How does urlregexps work?

### DISCUSSION THREAD

**Discussion by AnderssonPeter** [tomMoulard/fail2ban#66] [Q&A]
So I'm trying to write a `urlregexps` that blocks all requests that contain `/../` but I can't get it to work.
```yml
urlregexps:
- regexp: "\\.\\."
  mode: block
- regexp: "/\\.\\."
  mode: block
- regexp: ".*\\.\\..*"
  mode: block
```

Question number 2, does this just block the request or does it cause a ban?
If I add
```yml
urlregexps:
- regexp: "/no"
  mode: block
```
It works until I call `/no` after that all requests are yield 403.
