### ISSUE TITLE
Can't install plugins with line from documentation

### ISSUE THREAD

**Issue by Its-Alex** [tomMoulard/fail2ban#207]
Hello 👋

When I try to install this plugin I have an error:

```
traefik-1  | 2025-06-12T17:14:19Z INF github.com/traefik/traefik/v3/cmd/traefik/traefik.go:239 > Loading plugins... plugins=["tm-fail2ban"]
traefik-1  | 2025-06-12T17:14:19Z DBG github.com/traefik/traefik/v3/pkg/plugins/plugins.go:30 > Loading of plugin: tm-fail2ban: github.com/tomMoulard/fail2ban@v0.8.6
traefik-1  | 2025-06-12T17:14:19Z DBG github.com/hashicorp/go-retryablehttp@v0.7.7/client.go:661 > Performing request method=GET url=https://plugins.traefik.io/public/download/github.com/tomMoulard/fail2ban/v0.8.6
traefik-1  | 2025-06-12T17:14:19Z DBG github.com/hashicorp/go-retryablehttp@v0.7.7/client.go:762 > Retrying request remaining=3 request="GET https://plugins.traefik.io/public/download/github.com/tomMoulard/fail2ban/v0.8.6 (status: 500)" timeout=1s
traefik-1  | 2025-06-12T17:14:20Z DBG github.com/hashicorp/go-retryablehttp@v0.7.7/client.go:762 > Retrying request remaining=2 request="GET https://plugins.traefik.io/public/download/github.com/tomMoulard/fail2ban/v0.8.6 (status: 500)" timeout=2s
traefik-1  | 2025-06-12T17:14:22Z DBG github.com/hashicorp/go-retryablehttp@v0.7.7/client.go:762 > Retrying request remaining=1 request="GET https://plugins.traefik.io/public/download/github.com/tomMoulard/fail2ban/v0.8.6 (status: 500)" timeout=4s
traefik-1  | 2025-06-12T17:14:26Z ERR github.com/traefik/traefik/v3/cmd/traefik/traefik.go:247 > Plugins are disabled because an error has occurred. error="unable to set up plugins environment: unable to download plugin github.com/tomMoulard/fail2ban: failed to call service: Get \"https://plugins.traefik.io/public/download/github.com/tomMoulard/fail2ban/v0.8.6\": GET https://plugins.traefik.io/public/download/github.com/tomMoulard/fail2ban/v0.8.6 giving up after 4 attempt(s)" plugins=["tm-fail2ban"]
```

I used the following configuration to install the plugin:

```
experimental:
  plugins:
    tm-fail2ban:
      moduleName: "github.com/tomMoulard/fail2ban"
      version: "v0.8.6"
```

I tried with:

```
experimental:
  plugins:
    tm-fail2ban:
      moduleName: "github.com/tomMoulard/fail2ban"
      version: "v0.8.5"
```

And get the same error.

I saw https://github.com/tomMoulard/fail2ban/issues/136#issuecomment-2943801447 but I think this should be an independent issue. Do you have any idea why?
