### ISSUE TITLE
Ability to notify when an ip becomes banned

### ISSUE THREAD

**Issue by urbitech** [tomMoulard/fail2ban#50]
Hi, are there any plans to implement such feature using email/telegram/....? Thank you.

**Comment by tomMoulard** [comment]
This feature is not planned as of today, but it can be implemented. Feel free to open a PR !

**Comment by jnovack** [comment]
You can just get VERY simple with a bash script.

```bash
#!/bin/bash

LOG_FILE="/var/log/traefik.log" # Replace with your log file path
KEYWORD="fail2ban"             # Replace with the keyword to search for
RECIPIENT_EMAIL="your_email@example.com" # Replace with recipient email
SUBJECT="Log Alert: $KEYWORD found in $LOG_FILE"

tail -f "$LOG_FILE" | grep --line-buffered "$KEYWORD" | while read -r line; do
    echo "$line" | mail -s "$SUBJECT" "$RECIPIENT_EMAIL"
done
```

Up from that, you can use [Logwatch](https://wiki.archlinux.org/title/Logwatch). Or begin your journey collecting them with rsyslog, or syslog-ng.

When you understand the flow, and mastered it locally, you'll need to collect your logs in a centralized location with a service (ELK, SigNoz, Logz.io, Graylog, Logtail) and the centralized service (either hosted locally or in the cloud) sends the notifications based on rule sets.

**Comment by dberardo-com** [comment]
in general i believe it would be great to use the "action" semantic to do these kind of things ... in particular i believe it would be great to have a ban/unban action that at very least supports webhooks and basic templating, something like:

```yaml
actions:
 - event: banned
    type: webhook
    method: POST
    url: 
    body: .
- event: banned
    type: webhook
    method: GET
    url: http://another-service/ban?ip={{unbanned_ip}}
- event: unbanned
    type: webhook
    method: GET
    url: http://another-service/unban?ip={{unbanned_ip}}
```
this would make the whole thing quite generic and capable to use telegram notifications, as well as easily integrate with other pipelines.

in my use case i would need to propagate the banned ip to a whole other chain of services and so the webhook strategy could come in handy.
